Update apply-nap.yml

diff --git a/.github/workflows/apply-nap.yml b/.github/workflows/apply-nap.yml
--- a/.github/workflows/apply-nap.yml
+++ b/.github/workflows/apply-nap.yml
@@ -16,6 +16,7 @@ jobs:
     steps:
       - name: Checkout
         uses: actions/checkout@v3
+
       - name: Create Certificates Directory
         run: |
           sudo mkdir -p /etc/docker/certs.d/private-registry.nginx.com
@@ -63,7 +64,6 @@ jobs:
       - name: Terraform Apply
         if: github.ref == 'refs/heads/apply-nap' && github.event_name == 'push'
         run: terraform apply -auto-approve -input=false
-
 
   terraform_eks:
     name: "AWS EKS"
@@ -121,75 +121,75 @@ jobs:
         if: github.ref == 'refs/heads/apply-nap' && github.event_name == 'push'
         run: terraform apply -auto-approve -input=false
 
- terraform_nap:
-  name: "NGINX App Protect"
-  runs-on: ubuntu-latest
-  needs: terraform_eks
-  defaults:
-    run:
-      working-directory: ./nap
-  steps:
-    - name: Checkout
-      uses: actions/checkout@v3
+  terraform_nap:
+    name: "NGINX App Protect"
+    runs-on: ubuntu-latest
+    needs: terraform_eks
+    defaults:
+      run:
+        working-directory: ./nap
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v3
 
-    - name: Install Docker and Docker Compose
-      run: |
-        sudo yum update -y
-        sudo amazon-linux-extras install docker -y
-        sudo service docker start
-        sudo usermod -aG docker ec2-user
-        
-        # Install Docker Compose
-        sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
-        sudo chmod +x /usr/local/bin/docker-compose
-        docker --version  # Optional: Check Docker version
-        docker-compose --version  # Optional: Check Docker Compose version
+      - name: Install Docker and Docker Compose
+        run: |
+            sudo yum update -y
+            sudo amazon-linux-extras install docker -y
+            sudo service docker start
+            sudo usermod -aG docker ec2-user
+            
+            # Install Docker Compose
+            sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
+            sudo chmod +x /usr/local/bin/docker-compose
+            docker --version  # Optional: Check Docker version
+            docker-compose --version  # Optional: Check Docker Compose version
+          EOF
 
-    - name: Setup Terraform
-      uses: hashicorp/setup-terraform@v2
-      with:
-        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
+      - name: Setup Terraform
+        uses: hashicorp/setup-terraform@v2
+        with:
+          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
 
-    - name: Setup Terraform Backend
-      run: |
-        cat > backend.tf << EOF
-        terraform {
-          cloud {
-            organization = "${{ secrets.TF_CLOUD_ORGANIZATION }}"
-            workspaces {
-              name = "${{ secrets.TF_CLOUD_WORKSPACE_NAP }}"
+      - name: Setup Terraform Backend
+        run: |
+          cat > backend.tf << EOF
+          terraform {
+            cloud {
+              organization = "${{ secrets.TF_CLOUD_ORGANIZATION }}"
+              workspaces {
+                name = "${{ secrets.TF_CLOUD_WORKSPACE_NAP }}"
+              }
             }
           }
-        }
-        EOF
+          EOF
 
-    - name: Terraform Init
-      run: terraform init
+      - name: Terraform Init
+        run: terraform init
 
-    - name: Terraform Validate
-      run: terraform validate -no-color
+      - name: Terraform Validate
+        run: terraform validate -no-color
 
-    - name: Terraform Plan
-      if: github.event_name == 'pull_request'
-      run: |
-        export TF_LOG=DEBUG
-        terraform plan -no-color -input=false | tee plan.txt
-        cat plan.txt
-      continue-on-error: true
+      - name: Terraform Plan
+        if: github.event_name == 'pull_request'
+        run: |
+          export TF_LOG=DEBUG
+          terraform plan -no-color -input=false | tee plan.txt
+          cat plan.txt
+        continue-on-error: true
 
-    - name: Terraform Plan Status
-      run: |
-        if grep -q "Error" plan.txt; then
-          echo "❌ Terraform plan contains errors!"
-          exit 1
-        else
-          echo "✅ Terraform plan is clean!"
-        fi
+      - name: Terraform Plan Status
+        run: |
+          if grep -q "Error" plan.txt; then
+            echo "❌ Terraform plan contains errors!"
+            exit 1
+          else
+            echo "✅ Terraform plan is clean!"
+          fi
 
-    - name: Terraform Apply
-      if: github.ref == 'refs/heads/apply-nap' && github.event_name == 'push'
-      run: terraform apply -auto-approve -input=false
-
+      - name: Terraform Apply
+        if: github.ref == 'refs/heads/apply-nap' && github.event_name == 'push'
+        run: terraform apply -auto-approve -input=false
 
   terraform_arcadia:
     name: "Arcadia WebApp"
